// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.1
// source: api/proto/auth/auth.proto

package auth

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConfigService_UpsertClientConfig_FullMethodName = "/auth.ConfigService/UpsertClientConfig"
	ConfigService_DeleteClientConfig_FullMethodName = "/auth.ConfigService/DeleteClientConfig"
	ConfigService_GetClientConfig_FullMethodName    = "/auth.ConfigService/GetClientConfig"
	ConfigService_ListClientConfigs_FullMethodName  = "/auth.ConfigService/ListClientConfigs"
	ConfigService_BootstrapConfigs_FullMethodName   = "/auth.ConfigService/BootstrapConfigs"
)

// ConfigServiceClient is the client API for ConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ── ConfigService — مدیریت ClientConfig از طریق Raft ───────────────────────
type ConfigServiceClient interface {
	UpsertClientConfig(ctx context.Context, in *UpsertClientConfigRequest, opts ...grpc.CallOption) (*UpsertClientConfigResponse, error)
	DeleteClientConfig(ctx context.Context, in *DeleteClientConfigRequest, opts ...grpc.CallOption) (*DeleteClientConfigResponse, error)
	GetClientConfig(ctx context.Context, in *GetClientConfigRequest, opts ...grpc.CallOption) (*GetClientConfigResponse, error)
	ListClientConfigs(ctx context.Context, in *ListClientConfigsRequest, opts ...grpc.CallOption) (*ListClientConfigsResponse, error)
	BootstrapConfigs(ctx context.Context, in *BootstrapConfigsRequest, opts ...grpc.CallOption) (*BootstrapConfigsResponse, error)
}

type configServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigServiceClient(cc grpc.ClientConnInterface) ConfigServiceClient {
	return &configServiceClient{cc}
}

func (c *configServiceClient) UpsertClientConfig(ctx context.Context, in *UpsertClientConfigRequest, opts ...grpc.CallOption) (*UpsertClientConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertClientConfigResponse)
	err := c.cc.Invoke(ctx, ConfigService_UpsertClientConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) DeleteClientConfig(ctx context.Context, in *DeleteClientConfigRequest, opts ...grpc.CallOption) (*DeleteClientConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteClientConfigResponse)
	err := c.cc.Invoke(ctx, ConfigService_DeleteClientConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) GetClientConfig(ctx context.Context, in *GetClientConfigRequest, opts ...grpc.CallOption) (*GetClientConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClientConfigResponse)
	err := c.cc.Invoke(ctx, ConfigService_GetClientConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) ListClientConfigs(ctx context.Context, in *ListClientConfigsRequest, opts ...grpc.CallOption) (*ListClientConfigsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListClientConfigsResponse)
	err := c.cc.Invoke(ctx, ConfigService_ListClientConfigs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) BootstrapConfigs(ctx context.Context, in *BootstrapConfigsRequest, opts ...grpc.CallOption) (*BootstrapConfigsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BootstrapConfigsResponse)
	err := c.cc.Invoke(ctx, ConfigService_BootstrapConfigs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigServiceServer is the server API for ConfigService service.
// All implementations must embed UnimplementedConfigServiceServer
// for forward compatibility.
//
// ── ConfigService — مدیریت ClientConfig از طریق Raft ───────────────────────
type ConfigServiceServer interface {
	UpsertClientConfig(context.Context, *UpsertClientConfigRequest) (*UpsertClientConfigResponse, error)
	DeleteClientConfig(context.Context, *DeleteClientConfigRequest) (*DeleteClientConfigResponse, error)
	GetClientConfig(context.Context, *GetClientConfigRequest) (*GetClientConfigResponse, error)
	ListClientConfigs(context.Context, *ListClientConfigsRequest) (*ListClientConfigsResponse, error)
	BootstrapConfigs(context.Context, *BootstrapConfigsRequest) (*BootstrapConfigsResponse, error)
	mustEmbedUnimplementedConfigServiceServer()
}

// UnimplementedConfigServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConfigServiceServer struct{}

func (UnimplementedConfigServiceServer) UpsertClientConfig(context.Context, *UpsertClientConfigRequest) (*UpsertClientConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertClientConfig not implemented")
}
func (UnimplementedConfigServiceServer) DeleteClientConfig(context.Context, *DeleteClientConfigRequest) (*DeleteClientConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteClientConfig not implemented")
}
func (UnimplementedConfigServiceServer) GetClientConfig(context.Context, *GetClientConfigRequest) (*GetClientConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClientConfig not implemented")
}
func (UnimplementedConfigServiceServer) ListClientConfigs(context.Context, *ListClientConfigsRequest) (*ListClientConfigsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListClientConfigs not implemented")
}
func (UnimplementedConfigServiceServer) BootstrapConfigs(context.Context, *BootstrapConfigsRequest) (*BootstrapConfigsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BootstrapConfigs not implemented")
}
func (UnimplementedConfigServiceServer) mustEmbedUnimplementedConfigServiceServer() {}
func (UnimplementedConfigServiceServer) testEmbeddedByValue()                       {}

// UnsafeConfigServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigServiceServer will
// result in compilation errors.
type UnsafeConfigServiceServer interface {
	mustEmbedUnimplementedConfigServiceServer()
}

func RegisterConfigServiceServer(s grpc.ServiceRegistrar, srv ConfigServiceServer) {
	// If the following call panics, it indicates UnimplementedConfigServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConfigService_ServiceDesc, srv)
}

func _ConfigService_UpsertClientConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertClientConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).UpsertClientConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_UpsertClientConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).UpsertClientConfig(ctx, req.(*UpsertClientConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_DeleteClientConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteClientConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).DeleteClientConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_DeleteClientConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).DeleteClientConfig(ctx, req.(*DeleteClientConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_GetClientConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClientConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).GetClientConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_GetClientConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).GetClientConfig(ctx, req.(*GetClientConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_ListClientConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListClientConfigsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).ListClientConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_ListClientConfigs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).ListClientConfigs(ctx, req.(*ListClientConfigsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_BootstrapConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BootstrapConfigsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).BootstrapConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_BootstrapConfigs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).BootstrapConfigs(ctx, req.(*BootstrapConfigsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConfigService_ServiceDesc is the grpc.ServiceDesc for ConfigService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfigService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.ConfigService",
	HandlerType: (*ConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpsertClientConfig",
			Handler:    _ConfigService_UpsertClientConfig_Handler,
		},
		{
			MethodName: "DeleteClientConfig",
			Handler:    _ConfigService_DeleteClientConfig_Handler,
		},
		{
			MethodName: "GetClientConfig",
			Handler:    _ConfigService_GetClientConfig_Handler,
		},
		{
			MethodName: "ListClientConfigs",
			Handler:    _ConfigService_ListClientConfigs_Handler,
		},
		{
			MethodName: "BootstrapConfigs",
			Handler:    _ConfigService_BootstrapConfigs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/auth/auth.proto",
}
