// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: api/proto/auth/auth.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ── ClientConfig ────────────────────────────────────────────────────────────
type ClientConfig struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	Id                          int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SystemId                    string                 `protobuf:"bytes,2,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`
	PasswordHash                string                 `protobuf:"bytes,3,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	MaxConnections              int32                  `protobuf:"varint,4,opt,name=max_connections,json=maxConnections,proto3" json:"max_connections,omitempty"`
	TpsLimit                    int32                  `protobuf:"varint,5,opt,name=tps_limit,json=tpsLimit,proto3" json:"tps_limit,omitempty"`
	SubmitRespMessageIdType     string                 `protobuf:"bytes,6,opt,name=submit_resp_message_id_type,json=submitRespMessageIdType,proto3" json:"submit_resp_message_id_type,omitempty"`
	DeliveryReportMessageIdType string                 `protobuf:"bytes,7,opt,name=delivery_report_message_id_type,json=deliveryReportMessageIdType,proto3" json:"delivery_report_message_id_type,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *ClientConfig) Reset() {
	*x = ClientConfig{}
	mi := &file_api_proto_auth_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientConfig) ProtoMessage() {}

func (x *ClientConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientConfig.ProtoReflect.Descriptor instead.
func (*ClientConfig) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_proto_rawDescGZIP(), []int{0}
}

func (x *ClientConfig) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ClientConfig) GetSystemId() string {
	if x != nil {
		return x.SystemId
	}
	return ""
}

func (x *ClientConfig) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *ClientConfig) GetMaxConnections() int32 {
	if x != nil {
		return x.MaxConnections
	}
	return 0
}

func (x *ClientConfig) GetTpsLimit() int32 {
	if x != nil {
		return x.TpsLimit
	}
	return 0
}

func (x *ClientConfig) GetSubmitRespMessageIdType() string {
	if x != nil {
		return x.SubmitRespMessageIdType
	}
	return ""
}

func (x *ClientConfig) GetDeliveryReportMessageIdType() string {
	if x != nil {
		return x.DeliveryReportMessageIdType
	}
	return ""
}

type UpsertClientConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *ClientConfig          `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertClientConfigRequest) Reset() {
	*x = UpsertClientConfigRequest{}
	mi := &file_api_proto_auth_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertClientConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertClientConfigRequest) ProtoMessage() {}

func (x *UpsertClientConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertClientConfigRequest.ProtoReflect.Descriptor instead.
func (*UpsertClientConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_proto_rawDescGZIP(), []int{1}
}

func (x *UpsertClientConfigRequest) GetConfig() *ClientConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type UpsertClientConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     ErrorCode              `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=auth.ErrorCode" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertClientConfigResponse) Reset() {
	*x = UpsertClientConfigResponse{}
	mi := &file_api_proto_auth_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertClientConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertClientConfigResponse) ProtoMessage() {}

func (x *UpsertClientConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertClientConfigResponse.ProtoReflect.Descriptor instead.
func (*UpsertClientConfigResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_proto_rawDescGZIP(), []int{2}
}

func (x *UpsertClientConfigResponse) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_ERROR_CODE_NONE
}

func (x *UpsertClientConfigResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type DeleteClientConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SystemId      string                 `protobuf:"bytes,1,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteClientConfigRequest) Reset() {
	*x = DeleteClientConfigRequest{}
	mi := &file_api_proto_auth_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteClientConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClientConfigRequest) ProtoMessage() {}

func (x *DeleteClientConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClientConfigRequest.ProtoReflect.Descriptor instead.
func (*DeleteClientConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteClientConfigRequest) GetSystemId() string {
	if x != nil {
		return x.SystemId
	}
	return ""
}

type DeleteClientConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     ErrorCode              `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=auth.ErrorCode" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteClientConfigResponse) Reset() {
	*x = DeleteClientConfigResponse{}
	mi := &file_api_proto_auth_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteClientConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClientConfigResponse) ProtoMessage() {}

func (x *DeleteClientConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClientConfigResponse.ProtoReflect.Descriptor instead.
func (*DeleteClientConfigResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteClientConfigResponse) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_ERROR_CODE_NONE
}

func (x *DeleteClientConfigResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type GetClientConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SystemId      string                 `protobuf:"bytes,1,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientConfigRequest) Reset() {
	*x = GetClientConfigRequest{}
	mi := &file_api_proto_auth_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientConfigRequest) ProtoMessage() {}

func (x *GetClientConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientConfigRequest.ProtoReflect.Descriptor instead.
func (*GetClientConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_proto_rawDescGZIP(), []int{5}
}

func (x *GetClientConfigRequest) GetSystemId() string {
	if x != nil {
		return x.SystemId
	}
	return ""
}

type GetClientConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     ErrorCode              `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=auth.ErrorCode" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Config        *ClientConfig          `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientConfigResponse) Reset() {
	*x = GetClientConfigResponse{}
	mi := &file_api_proto_auth_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientConfigResponse) ProtoMessage() {}

func (x *GetClientConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientConfigResponse.ProtoReflect.Descriptor instead.
func (*GetClientConfigResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_proto_rawDescGZIP(), []int{6}
}

func (x *GetClientConfigResponse) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_ERROR_CODE_NONE
}

func (x *GetClientConfigResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *GetClientConfigResponse) GetConfig() *ClientConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type ListClientConfigsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClientConfigsRequest) Reset() {
	*x = ListClientConfigsRequest{}
	mi := &file_api_proto_auth_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClientConfigsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClientConfigsRequest) ProtoMessage() {}

func (x *ListClientConfigsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClientConfigsRequest.ProtoReflect.Descriptor instead.
func (*ListClientConfigsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_proto_rawDescGZIP(), []int{7}
}

type ListClientConfigsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     ErrorCode              `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=auth.ErrorCode" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Configs       []*ClientConfig        `protobuf:"bytes,3,rep,name=configs,proto3" json:"configs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClientConfigsResponse) Reset() {
	*x = ListClientConfigsResponse{}
	mi := &file_api_proto_auth_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClientConfigsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClientConfigsResponse) ProtoMessage() {}

func (x *ListClientConfigsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClientConfigsResponse.ProtoReflect.Descriptor instead.
func (*ListClientConfigsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_proto_rawDescGZIP(), []int{8}
}

func (x *ListClientConfigsResponse) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_ERROR_CODE_NONE
}

func (x *ListClientConfigsResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ListClientConfigsResponse) GetConfigs() []*ClientConfig {
	if x != nil {
		return x.Configs
	}
	return nil
}

type BootstrapConfigsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configs       []*ClientConfig        `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapConfigsRequest) Reset() {
	*x = BootstrapConfigsRequest{}
	mi := &file_api_proto_auth_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapConfigsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapConfigsRequest) ProtoMessage() {}

func (x *BootstrapConfigsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapConfigsRequest.ProtoReflect.Descriptor instead.
func (*BootstrapConfigsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_proto_rawDescGZIP(), []int{9}
}

func (x *BootstrapConfigsRequest) GetConfigs() []*ClientConfig {
	if x != nil {
		return x.Configs
	}
	return nil
}

type BootstrapConfigsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     ErrorCode              `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=auth.ErrorCode" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	LoadedCount   int32                  `protobuf:"varint,3,opt,name=loaded_count,json=loadedCount,proto3" json:"loaded_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapConfigsResponse) Reset() {
	*x = BootstrapConfigsResponse{}
	mi := &file_api_proto_auth_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapConfigsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapConfigsResponse) ProtoMessage() {}

func (x *BootstrapConfigsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapConfigsResponse.ProtoReflect.Descriptor instead.
func (*BootstrapConfigsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_proto_rawDescGZIP(), []int{10}
}

func (x *BootstrapConfigsResponse) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_ERROR_CODE_NONE
}

func (x *BootstrapConfigsResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *BootstrapConfigsResponse) GetLoadedCount() int32 {
	if x != nil {
		return x.LoadedCount
	}
	return 0
}

var File_api_proto_auth_auth_proto protoreflect.FileDescriptor

const file_api_proto_auth_auth_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/auth/auth.proto\x12\x04auth\x1a\x1bapi/proto/auth/common.proto\"\xaa\x02\n" +
	"\fClientConfig\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tsystem_id\x18\x02 \x01(\tR\bsystemId\x12#\n" +
	"\rpassword_hash\x18\x03 \x01(\tR\fpasswordHash\x12'\n" +
	"\x0fmax_connections\x18\x04 \x01(\x05R\x0emaxConnections\x12\x1b\n" +
	"\ttps_limit\x18\x05 \x01(\x05R\btpsLimit\x12<\n" +
	"\x1bsubmit_resp_message_id_type\x18\x06 \x01(\tR\x17submitRespMessageIdType\x12D\n" +
	"\x1fdelivery_report_message_id_type\x18\a \x01(\tR\x1bdeliveryReportMessageIdType\"G\n" +
	"\x19UpsertClientConfigRequest\x12*\n" +
	"\x06config\x18\x01 \x01(\v2\x12.auth.ClientConfigR\x06config\"q\n" +
	"\x1aUpsertClientConfigResponse\x12.\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x0e2\x0f.auth.ErrorCodeR\terrorCode\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"8\n" +
	"\x19DeleteClientConfigRequest\x12\x1b\n" +
	"\tsystem_id\x18\x01 \x01(\tR\bsystemId\"q\n" +
	"\x1aDeleteClientConfigResponse\x12.\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x0e2\x0f.auth.ErrorCodeR\terrorCode\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"5\n" +
	"\x16GetClientConfigRequest\x12\x1b\n" +
	"\tsystem_id\x18\x01 \x01(\tR\bsystemId\"\x9a\x01\n" +
	"\x17GetClientConfigResponse\x12.\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x0e2\x0f.auth.ErrorCodeR\terrorCode\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12*\n" +
	"\x06config\x18\x03 \x01(\v2\x12.auth.ClientConfigR\x06config\"\x1a\n" +
	"\x18ListClientConfigsRequest\"\x9e\x01\n" +
	"\x19ListClientConfigsResponse\x12.\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x0e2\x0f.auth.ErrorCodeR\terrorCode\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12,\n" +
	"\aconfigs\x18\x03 \x03(\v2\x12.auth.ClientConfigR\aconfigs\"G\n" +
	"\x17BootstrapConfigsRequest\x12,\n" +
	"\aconfigs\x18\x01 \x03(\v2\x12.auth.ClientConfigR\aconfigs\"\x92\x01\n" +
	"\x18BootstrapConfigsResponse\x12.\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x0e2\x0f.auth.ErrorCodeR\terrorCode\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12!\n" +
	"\floaded_count\x18\x03 \x01(\x05R\vloadedCount2\xba\x03\n" +
	"\rConfigService\x12W\n" +
	"\x12UpsertClientConfig\x12\x1f.auth.UpsertClientConfigRequest\x1a .auth.UpsertClientConfigResponse\x12W\n" +
	"\x12DeleteClientConfig\x12\x1f.auth.DeleteClientConfigRequest\x1a .auth.DeleteClientConfigResponse\x12N\n" +
	"\x0fGetClientConfig\x12\x1c.auth.GetClientConfigRequest\x1a\x1d.auth.GetClientConfigResponse\x12T\n" +
	"\x11ListClientConfigs\x12\x1e.auth.ListClientConfigsRequest\x1a\x1f.auth.ListClientConfigsResponse\x12Q\n" +
	"\x10BootstrapConfigs\x12\x1d.auth.BootstrapConfigsRequest\x1a\x1e.auth.BootstrapConfigsResponseB#Z!authenticator/api/proto/auth;authb\x06proto3"

var (
	file_api_proto_auth_auth_proto_rawDescOnce sync.Once
	file_api_proto_auth_auth_proto_rawDescData []byte
)

func file_api_proto_auth_auth_proto_rawDescGZIP() []byte {
	file_api_proto_auth_auth_proto_rawDescOnce.Do(func() {
		file_api_proto_auth_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_auth_auth_proto_rawDesc), len(file_api_proto_auth_auth_proto_rawDesc)))
	})
	return file_api_proto_auth_auth_proto_rawDescData
}

var file_api_proto_auth_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_proto_auth_auth_proto_goTypes = []any{
	(*ClientConfig)(nil),               // 0: auth.ClientConfig
	(*UpsertClientConfigRequest)(nil),  // 1: auth.UpsertClientConfigRequest
	(*UpsertClientConfigResponse)(nil), // 2: auth.UpsertClientConfigResponse
	(*DeleteClientConfigRequest)(nil),  // 3: auth.DeleteClientConfigRequest
	(*DeleteClientConfigResponse)(nil), // 4: auth.DeleteClientConfigResponse
	(*GetClientConfigRequest)(nil),     // 5: auth.GetClientConfigRequest
	(*GetClientConfigResponse)(nil),    // 6: auth.GetClientConfigResponse
	(*ListClientConfigsRequest)(nil),   // 7: auth.ListClientConfigsRequest
	(*ListClientConfigsResponse)(nil),  // 8: auth.ListClientConfigsResponse
	(*BootstrapConfigsRequest)(nil),    // 9: auth.BootstrapConfigsRequest
	(*BootstrapConfigsResponse)(nil),   // 10: auth.BootstrapConfigsResponse
	(ErrorCode)(0),                     // 11: auth.ErrorCode
}
var file_api_proto_auth_auth_proto_depIdxs = []int32{
	0,  // 0: auth.UpsertClientConfigRequest.config:type_name -> auth.ClientConfig
	11, // 1: auth.UpsertClientConfigResponse.error_code:type_name -> auth.ErrorCode
	11, // 2: auth.DeleteClientConfigResponse.error_code:type_name -> auth.ErrorCode
	11, // 3: auth.GetClientConfigResponse.error_code:type_name -> auth.ErrorCode
	0,  // 4: auth.GetClientConfigResponse.config:type_name -> auth.ClientConfig
	11, // 5: auth.ListClientConfigsResponse.error_code:type_name -> auth.ErrorCode
	0,  // 6: auth.ListClientConfigsResponse.configs:type_name -> auth.ClientConfig
	0,  // 7: auth.BootstrapConfigsRequest.configs:type_name -> auth.ClientConfig
	11, // 8: auth.BootstrapConfigsResponse.error_code:type_name -> auth.ErrorCode
	1,  // 9: auth.ConfigService.UpsertClientConfig:input_type -> auth.UpsertClientConfigRequest
	3,  // 10: auth.ConfigService.DeleteClientConfig:input_type -> auth.DeleteClientConfigRequest
	5,  // 11: auth.ConfigService.GetClientConfig:input_type -> auth.GetClientConfigRequest
	7,  // 12: auth.ConfigService.ListClientConfigs:input_type -> auth.ListClientConfigsRequest
	9,  // 13: auth.ConfigService.BootstrapConfigs:input_type -> auth.BootstrapConfigsRequest
	2,  // 14: auth.ConfigService.UpsertClientConfig:output_type -> auth.UpsertClientConfigResponse
	4,  // 15: auth.ConfigService.DeleteClientConfig:output_type -> auth.DeleteClientConfigResponse
	6,  // 16: auth.ConfigService.GetClientConfig:output_type -> auth.GetClientConfigResponse
	8,  // 17: auth.ConfigService.ListClientConfigs:output_type -> auth.ListClientConfigsResponse
	10, // 18: auth.ConfigService.BootstrapConfigs:output_type -> auth.BootstrapConfigsResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_proto_auth_auth_proto_init() }
func file_api_proto_auth_auth_proto_init() {
	if File_api_proto_auth_auth_proto != nil {
		return
	}
	file_api_proto_auth_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_auth_auth_proto_rawDesc), len(file_api_proto_auth_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_auth_auth_proto_goTypes,
		DependencyIndexes: file_api_proto_auth_auth_proto_depIdxs,
		MessageInfos:      file_api_proto_auth_auth_proto_msgTypes,
	}.Build()
	File_api_proto_auth_auth_proto = out.File
	file_api_proto_auth_auth_proto_goTypes = nil
	file_api_proto_auth_auth_proto_depIdxs = nil
}
