// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: api/proto/auth/common.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BindType int32

const (
	BindType_BIND_TYPE_UNKNOWN     BindType = 0
	BindType_BIND_TYPE_RECEIVER    BindType = 1
	BindType_BIND_TYPE_TRANSMITTER BindType = 2
	BindType_BIND_TYPE_TRANSCEIVER BindType = 9
)

// Enum value maps for BindType.
var (
	BindType_name = map[int32]string{
		0: "BIND_TYPE_UNKNOWN",
		1: "BIND_TYPE_RECEIVER",
		2: "BIND_TYPE_TRANSMITTER",
		9: "BIND_TYPE_TRANSCEIVER",
	}
	BindType_value = map[string]int32{
		"BIND_TYPE_UNKNOWN":     0,
		"BIND_TYPE_RECEIVER":    1,
		"BIND_TYPE_TRANSMITTER": 2,
		"BIND_TYPE_TRANSCEIVER": 9,
	}
)

func (x BindType) Enum() *BindType {
	p := new(BindType)
	*p = x
	return p
}

func (x BindType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BindType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_auth_common_proto_enumTypes[0].Descriptor()
}

func (BindType) Type() protoreflect.EnumType {
	return &file_api_proto_auth_common_proto_enumTypes[0]
}

func (x BindType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BindType.Descriptor instead.
func (BindType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_auth_common_proto_rawDescGZIP(), []int{0}
}

type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_NONE                      ErrorCode = 0
	ErrorCode_ERROR_CODE_SUCCESS                   ErrorCode = 1
	ErrorCode_ERROR_CODE_INTERNAL                  ErrorCode = 100
	ErrorCode_ERROR_CODE_SERVICE_UNAVAILABLE       ErrorCode = 103
	ErrorCode_ERROR_CODE_MISSING_REQUESTER_ID      ErrorCode = 600
	ErrorCode_ERROR_CODE_MISSING_SYSTEM_ID         ErrorCode = 601
	ErrorCode_ERROR_CODE_INVALID_SOURCE_IP         ErrorCode = 604
	ErrorCode_ERROR_CODE_INVALID_BIND_TYPE         ErrorCode = 605
	ErrorCode_ERROR_CODE_MAX_CONNECTIONS_REACHED   ErrorCode = 400
	ErrorCode_ERROR_CODE_CONNECTION_NOT_FOUND      ErrorCode = 500
	ErrorCode_ERROR_CODE_CONNECTION_ALREADY_CLOSED ErrorCode = 501
	ErrorCode_ERROR_CODE_INVALID_CONNECTION_ID     ErrorCode = 503
	ErrorCode_ERROR_CODE_CONFIG_NOT_FOUND          ErrorCode = 700
	ErrorCode_ERROR_CODE_CONFIG_INCONSISTENT       ErrorCode = 701
	ErrorCode_ERROR_CODE_NOT_LEADER                ErrorCode = 900
	ErrorCode_ERROR_CODE_LEADER_UNKNOWN            ErrorCode = 901
	ErrorCode_ERROR_CODE_CLUSTER_UNAVAILABLE       ErrorCode = 902
	ErrorCode_ERROR_CODE_RAFT_APPLY_FAILED         ErrorCode = 903
	ErrorCode_ERROR_CODE_NODE_ALREADY_EXISTS       ErrorCode = 904
	ErrorCode_ERROR_CODE_NODE_NOT_FOUND            ErrorCode = 905
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:   "ERROR_CODE_NONE",
		1:   "ERROR_CODE_SUCCESS",
		100: "ERROR_CODE_INTERNAL",
		103: "ERROR_CODE_SERVICE_UNAVAILABLE",
		600: "ERROR_CODE_MISSING_REQUESTER_ID",
		601: "ERROR_CODE_MISSING_SYSTEM_ID",
		604: "ERROR_CODE_INVALID_SOURCE_IP",
		605: "ERROR_CODE_INVALID_BIND_TYPE",
		400: "ERROR_CODE_MAX_CONNECTIONS_REACHED",
		500: "ERROR_CODE_CONNECTION_NOT_FOUND",
		501: "ERROR_CODE_CONNECTION_ALREADY_CLOSED",
		503: "ERROR_CODE_INVALID_CONNECTION_ID",
		700: "ERROR_CODE_CONFIG_NOT_FOUND",
		701: "ERROR_CODE_CONFIG_INCONSISTENT",
		900: "ERROR_CODE_NOT_LEADER",
		901: "ERROR_CODE_LEADER_UNKNOWN",
		902: "ERROR_CODE_CLUSTER_UNAVAILABLE",
		903: "ERROR_CODE_RAFT_APPLY_FAILED",
		904: "ERROR_CODE_NODE_ALREADY_EXISTS",
		905: "ERROR_CODE_NODE_NOT_FOUND",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_NONE":                      0,
		"ERROR_CODE_SUCCESS":                   1,
		"ERROR_CODE_INTERNAL":                  100,
		"ERROR_CODE_SERVICE_UNAVAILABLE":       103,
		"ERROR_CODE_MISSING_REQUESTER_ID":      600,
		"ERROR_CODE_MISSING_SYSTEM_ID":         601,
		"ERROR_CODE_INVALID_SOURCE_IP":         604,
		"ERROR_CODE_INVALID_BIND_TYPE":         605,
		"ERROR_CODE_MAX_CONNECTIONS_REACHED":   400,
		"ERROR_CODE_CONNECTION_NOT_FOUND":      500,
		"ERROR_CODE_CONNECTION_ALREADY_CLOSED": 501,
		"ERROR_CODE_INVALID_CONNECTION_ID":     503,
		"ERROR_CODE_CONFIG_NOT_FOUND":          700,
		"ERROR_CODE_CONFIG_INCONSISTENT":       701,
		"ERROR_CODE_NOT_LEADER":                900,
		"ERROR_CODE_LEADER_UNKNOWN":            901,
		"ERROR_CODE_CLUSTER_UNAVAILABLE":       902,
		"ERROR_CODE_RAFT_APPLY_FAILED":         903,
		"ERROR_CODE_NODE_ALREADY_EXISTS":       904,
		"ERROR_CODE_NODE_NOT_FOUND":            905,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_auth_common_proto_enumTypes[1].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_api_proto_auth_common_proto_enumTypes[1]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_auth_common_proto_rawDescGZIP(), []int{1}
}

var File_api_proto_auth_common_proto protoreflect.FileDescriptor

const file_api_proto_auth_common_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/proto/auth/common.proto\x12\x04auth*o\n" +
	"\bBindType\x12\x15\n" +
	"\x11BIND_TYPE_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12BIND_TYPE_RECEIVER\x10\x01\x12\x19\n" +
	"\x15BIND_TYPE_TRANSMITTER\x10\x02\x12\x19\n" +
	"\x15BIND_TYPE_TRANSCEIVER\x10\t*\xb5\x05\n" +
	"\tErrorCode\x12\x13\n" +
	"\x0fERROR_CODE_NONE\x10\x00\x12\x16\n" +
	"\x12ERROR_CODE_SUCCESS\x10\x01\x12\x17\n" +
	"\x13ERROR_CODE_INTERNAL\x10d\x12\"\n" +
	"\x1eERROR_CODE_SERVICE_UNAVAILABLE\x10g\x12$\n" +
	"\x1fERROR_CODE_MISSING_REQUESTER_ID\x10\xd8\x04\x12!\n" +
	"\x1cERROR_CODE_MISSING_SYSTEM_ID\x10\xd9\x04\x12!\n" +
	"\x1cERROR_CODE_INVALID_SOURCE_IP\x10\xdc\x04\x12!\n" +
	"\x1cERROR_CODE_INVALID_BIND_TYPE\x10\xdd\x04\x12'\n" +
	"\"ERROR_CODE_MAX_CONNECTIONS_REACHED\x10\x90\x03\x12$\n" +
	"\x1fERROR_CODE_CONNECTION_NOT_FOUND\x10\xf4\x03\x12)\n" +
	"$ERROR_CODE_CONNECTION_ALREADY_CLOSED\x10\xf5\x03\x12%\n" +
	" ERROR_CODE_INVALID_CONNECTION_ID\x10\xf7\x03\x12 \n" +
	"\x1bERROR_CODE_CONFIG_NOT_FOUND\x10\xbc\x05\x12#\n" +
	"\x1eERROR_CODE_CONFIG_INCONSISTENT\x10\xbd\x05\x12\x1a\n" +
	"\x15ERROR_CODE_NOT_LEADER\x10\x84\a\x12\x1e\n" +
	"\x19ERROR_CODE_LEADER_UNKNOWN\x10\x85\a\x12#\n" +
	"\x1eERROR_CODE_CLUSTER_UNAVAILABLE\x10\x86\a\x12!\n" +
	"\x1cERROR_CODE_RAFT_APPLY_FAILED\x10\x87\a\x12#\n" +
	"\x1eERROR_CODE_NODE_ALREADY_EXISTS\x10\x88\a\x12\x1e\n" +
	"\x19ERROR_CODE_NODE_NOT_FOUND\x10\x89\aB#Z!authenticator/api/proto/auth;authb\x06proto3"

var (
	file_api_proto_auth_common_proto_rawDescOnce sync.Once
	file_api_proto_auth_common_proto_rawDescData []byte
)

func file_api_proto_auth_common_proto_rawDescGZIP() []byte {
	file_api_proto_auth_common_proto_rawDescOnce.Do(func() {
		file_api_proto_auth_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_auth_common_proto_rawDesc), len(file_api_proto_auth_common_proto_rawDesc)))
	})
	return file_api_proto_auth_common_proto_rawDescData
}

var file_api_proto_auth_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_auth_common_proto_goTypes = []any{
	(BindType)(0),  // 0: auth.BindType
	(ErrorCode)(0), // 1: auth.ErrorCode
}
var file_api_proto_auth_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_auth_common_proto_init() }
func file_api_proto_auth_common_proto_init() {
	if File_api_proto_auth_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_auth_common_proto_rawDesc), len(file_api_proto_auth_common_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_auth_common_proto_goTypes,
		DependencyIndexes: file_api_proto_auth_common_proto_depIdxs,
		EnumInfos:         file_api_proto_auth_common_proto_enumTypes,
	}.Build()
	File_api_proto_auth_common_proto = out.File
	file_api_proto_auth_common_proto_goTypes = nil
	file_api_proto_auth_common_proto_depIdxs = nil
}
