// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: api/proto/auth/connection.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequesterId   string                 `protobuf:"bytes,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	SourceIp      string                 `protobuf:"bytes,2,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	BindType      BindType               `protobuf:"varint,3,opt,name=bind_type,json=bindType,proto3,enum=auth.BindType" json:"bind_type,omitempty"`
	SystemId      string                 `protobuf:"bytes,4,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`
	SystemType    string                 `protobuf:"bytes,5,opt,name=system_type,json=systemType,proto3" json:"system_type,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterConnectionRequest) Reset() {
	*x = RegisterConnectionRequest{}
	mi := &file_api_proto_auth_connection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterConnectionRequest) ProtoMessage() {}

func (x *RegisterConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_connection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterConnectionRequest.ProtoReflect.Descriptor instead.
func (*RegisterConnectionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_connection_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterConnectionRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

func (x *RegisterConnectionRequest) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *RegisterConnectionRequest) GetBindType() BindType {
	if x != nil {
		return x.BindType
	}
	return BindType_BIND_TYPE_UNKNOWN
}

func (x *RegisterConnectionRequest) GetSystemId() string {
	if x != nil {
		return x.SystemId
	}
	return ""
}

func (x *RegisterConnectionRequest) GetSystemType() string {
	if x != nil {
		return x.SystemType
	}
	return ""
}

func (x *RegisterConnectionRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type RegisterConnectionResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	AuthenticatorId       string                 `protobuf:"bytes,1,opt,name=authenticator_id,json=authenticatorId,proto3" json:"authenticator_id,omitempty"`
	ErrorCode             ErrorCode              `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3,enum=auth.ErrorCode" json:"error_code,omitempty"`
	ErrorMessage          string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ActiveConnections     int32                  `protobuf:"varint,4,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	MaxConnectionsAllowed int32                  `protobuf:"varint,5,opt,name=max_connections_allowed,json=maxConnectionsAllowed,proto3" json:"max_connections_allowed,omitempty"`
	ConnectionId          int64                  `protobuf:"varint,6,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RegisterConnectionResponse) Reset() {
	*x = RegisterConnectionResponse{}
	mi := &file_api_proto_auth_connection_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterConnectionResponse) ProtoMessage() {}

func (x *RegisterConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_connection_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterConnectionResponse.ProtoReflect.Descriptor instead.
func (*RegisterConnectionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_connection_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterConnectionResponse) GetAuthenticatorId() string {
	if x != nil {
		return x.AuthenticatorId
	}
	return ""
}

func (x *RegisterConnectionResponse) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_ERROR_CODE_NONE
}

func (x *RegisterConnectionResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *RegisterConnectionResponse) GetActiveConnections() int32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *RegisterConnectionResponse) GetMaxConnectionsAllowed() int32 {
	if x != nil {
		return x.MaxConnectionsAllowed
	}
	return 0
}

func (x *RegisterConnectionResponse) GetConnectionId() int64 {
	if x != nil {
		return x.ConnectionId
	}
	return 0
}

type UnregisterConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequesterId   string                 `protobuf:"bytes,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	ConnectionId  int64                  `protobuf:"varint,2,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterConnectionRequest) Reset() {
	*x = UnregisterConnectionRequest{}
	mi := &file_api_proto_auth_connection_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterConnectionRequest) ProtoMessage() {}

func (x *UnregisterConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_connection_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterConnectionRequest.ProtoReflect.Descriptor instead.
func (*UnregisterConnectionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_connection_proto_rawDescGZIP(), []int{2}
}

func (x *UnregisterConnectionRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

func (x *UnregisterConnectionRequest) GetConnectionId() int64 {
	if x != nil {
		return x.ConnectionId
	}
	return 0
}

func (x *UnregisterConnectionRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type UnregisterConnectionResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AuthenticatorId   string                 `protobuf:"bytes,1,opt,name=authenticator_id,json=authenticatorId,proto3" json:"authenticator_id,omitempty"`
	ErrorCode         ErrorCode              `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3,enum=auth.ErrorCode" json:"error_code,omitempty"`
	ErrorMessage      string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ActiveConnections int32                  `protobuf:"varint,4,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UnregisterConnectionResponse) Reset() {
	*x = UnregisterConnectionResponse{}
	mi := &file_api_proto_auth_connection_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterConnectionResponse) ProtoMessage() {}

func (x *UnregisterConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_connection_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterConnectionResponse.ProtoReflect.Descriptor instead.
func (*UnregisterConnectionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_connection_proto_rawDescGZIP(), []int{3}
}

func (x *UnregisterConnectionResponse) GetAuthenticatorId() string {
	if x != nil {
		return x.AuthenticatorId
	}
	return ""
}

func (x *UnregisterConnectionResponse) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_ERROR_CODE_NONE
}

func (x *UnregisterConnectionResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *UnregisterConnectionResponse) GetActiveConnections() int32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

type UnregisterAllConnectionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequesterId   string                 `protobuf:"bytes,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterAllConnectionsRequest) Reset() {
	*x = UnregisterAllConnectionsRequest{}
	mi := &file_api_proto_auth_connection_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterAllConnectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterAllConnectionsRequest) ProtoMessage() {}

func (x *UnregisterAllConnectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_connection_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterAllConnectionsRequest.ProtoReflect.Descriptor instead.
func (*UnregisterAllConnectionsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_connection_proto_rawDescGZIP(), []int{4}
}

func (x *UnregisterAllConnectionsRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

func (x *UnregisterAllConnectionsRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type UnregisterAllConnectionsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AuthenticatorId string                 `protobuf:"bytes,1,opt,name=authenticator_id,json=authenticatorId,proto3" json:"authenticator_id,omitempty"`
	ErrorCode       ErrorCode              `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3,enum=auth.ErrorCode" json:"error_code,omitempty"`
	ErrorMessage    string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UnregisterAllConnectionsResponse) Reset() {
	*x = UnregisterAllConnectionsResponse{}
	mi := &file_api_proto_auth_connection_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterAllConnectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterAllConnectionsResponse) ProtoMessage() {}

func (x *UnregisterAllConnectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_connection_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterAllConnectionsResponse.ProtoReflect.Descriptor instead.
func (*UnregisterAllConnectionsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_connection_proto_rawDescGZIP(), []int{5}
}

func (x *UnregisterAllConnectionsResponse) GetAuthenticatorId() string {
	if x != nil {
		return x.AuthenticatorId
	}
	return ""
}

func (x *UnregisterAllConnectionsResponse) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_ERROR_CODE_NONE
}

func (x *UnregisterAllConnectionsResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ListConnectionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequesterId   string                 `protobuf:"bytes,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	SystemId      string                 `protobuf:"bytes,2,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConnectionsRequest) Reset() {
	*x = ListConnectionsRequest{}
	mi := &file_api_proto_auth_connection_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConnectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConnectionsRequest) ProtoMessage() {}

func (x *ListConnectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_connection_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConnectionsRequest.ProtoReflect.Descriptor instead.
func (*ListConnectionsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_connection_proto_rawDescGZIP(), []int{6}
}

func (x *ListConnectionsRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

func (x *ListConnectionsRequest) GetSystemId() string {
	if x != nil {
		return x.SystemId
	}
	return ""
}

func (x *ListConnectionsRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ConnectionInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientConfigId  int64                  `protobuf:"varint,2,opt,name=client_config_id,json=clientConfigId,proto3" json:"client_config_id,omitempty"`
	SourceIp        string                 `protobuf:"bytes,3,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	BindType        BindType               `protobuf:"varint,4,opt,name=bind_type,json=bindType,proto3,enum=auth.BindType" json:"bind_type,omitempty"`
	ConnectedAt     int64                  `protobuf:"varint,5,opt,name=connected_at,json=connectedAt,proto3" json:"connected_at,omitempty"`
	DisconnectedAt  int64                  `protobuf:"varint,6,opt,name=disconnected_at,json=disconnectedAt,proto3" json:"disconnected_at,omitempty"`
	AuthenticatorId string                 `protobuf:"bytes,7,opt,name=authenticator_id,json=authenticatorId,proto3" json:"authenticator_id,omitempty"`
	RequesterId     string                 `protobuf:"bytes,8,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConnectionInfo) Reset() {
	*x = ConnectionInfo{}
	mi := &file_api_proto_auth_connection_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionInfo) ProtoMessage() {}

func (x *ConnectionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_connection_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionInfo.ProtoReflect.Descriptor instead.
func (*ConnectionInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_connection_proto_rawDescGZIP(), []int{7}
}

func (x *ConnectionInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ConnectionInfo) GetClientConfigId() int64 {
	if x != nil {
		return x.ClientConfigId
	}
	return 0
}

func (x *ConnectionInfo) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *ConnectionInfo) GetBindType() BindType {
	if x != nil {
		return x.BindType
	}
	return BindType_BIND_TYPE_UNKNOWN
}

func (x *ConnectionInfo) GetConnectedAt() int64 {
	if x != nil {
		return x.ConnectedAt
	}
	return 0
}

func (x *ConnectionInfo) GetDisconnectedAt() int64 {
	if x != nil {
		return x.DisconnectedAt
	}
	return 0
}

func (x *ConnectionInfo) GetAuthenticatorId() string {
	if x != nil {
		return x.AuthenticatorId
	}
	return ""
}

func (x *ConnectionInfo) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

type ListConnectionsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AuthenticatorId string                 `protobuf:"bytes,1,opt,name=authenticator_id,json=authenticatorId,proto3" json:"authenticator_id,omitempty"`
	ErrorCode       ErrorCode              `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3,enum=auth.ErrorCode" json:"error_code,omitempty"`
	ErrorMessage    string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Connections     []*ConnectionInfo      `protobuf:"bytes,4,rep,name=connections,proto3" json:"connections,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListConnectionsResponse) Reset() {
	*x = ListConnectionsResponse{}
	mi := &file_api_proto_auth_connection_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConnectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConnectionsResponse) ProtoMessage() {}

func (x *ListConnectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_connection_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConnectionsResponse.ProtoReflect.Descriptor instead.
func (*ListConnectionsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_connection_proto_rawDescGZIP(), []int{8}
}

func (x *ListConnectionsResponse) GetAuthenticatorId() string {
	if x != nil {
		return x.AuthenticatorId
	}
	return ""
}

func (x *ListConnectionsResponse) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_ERROR_CODE_NONE
}

func (x *ListConnectionsResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ListConnectionsResponse) GetConnections() []*ConnectionInfo {
	if x != nil {
		return x.Connections
	}
	return nil
}

var File_api_proto_auth_connection_proto protoreflect.FileDescriptor

const file_api_proto_auth_connection_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/proto/auth/connection.proto\x12\x04auth\x1a\x1bapi/proto/auth/common.proto\"\xe4\x01\n" +
	"\x19RegisterConnectionRequest\x12!\n" +
	"\frequester_id\x18\x01 \x01(\tR\vrequesterId\x12\x1b\n" +
	"\tsource_ip\x18\x02 \x01(\tR\bsourceIp\x12+\n" +
	"\tbind_type\x18\x03 \x01(\x0e2\x0e.auth.BindTypeR\bbindType\x12\x1b\n" +
	"\tsystem_id\x18\x04 \x01(\tR\bsystemId\x12\x1f\n" +
	"\vsystem_type\x18\x05 \x01(\tR\n" +
	"systemType\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"\xa8\x02\n" +
	"\x1aRegisterConnectionResponse\x12)\n" +
	"\x10authenticator_id\x18\x01 \x01(\tR\x0fauthenticatorId\x12.\n" +
	"\n" +
	"error_code\x18\x02 \x01(\x0e2\x0f.auth.ErrorCodeR\terrorCode\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12-\n" +
	"\x12active_connections\x18\x04 \x01(\x05R\x11activeConnections\x126\n" +
	"\x17max_connections_allowed\x18\x05 \x01(\x05R\x15maxConnectionsAllowed\x12#\n" +
	"\rconnection_id\x18\x06 \x01(\x03R\fconnectionId\"\x83\x01\n" +
	"\x1bUnregisterConnectionRequest\x12!\n" +
	"\frequester_id\x18\x01 \x01(\tR\vrequesterId\x12#\n" +
	"\rconnection_id\x18\x02 \x01(\x03R\fconnectionId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"\xcd\x01\n" +
	"\x1cUnregisterConnectionResponse\x12)\n" +
	"\x10authenticator_id\x18\x01 \x01(\tR\x0fauthenticatorId\x12.\n" +
	"\n" +
	"error_code\x18\x02 \x01(\x0e2\x0f.auth.ErrorCodeR\terrorCode\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12-\n" +
	"\x12active_connections\x18\x04 \x01(\x05R\x11activeConnections\"b\n" +
	"\x1fUnregisterAllConnectionsRequest\x12!\n" +
	"\frequester_id\x18\x01 \x01(\tR\vrequesterId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"\xa2\x01\n" +
	" UnregisterAllConnectionsResponse\x12)\n" +
	"\x10authenticator_id\x18\x01 \x01(\tR\x0fauthenticatorId\x12.\n" +
	"\n" +
	"error_code\x18\x02 \x01(\x0e2\x0f.auth.ErrorCodeR\terrorCode\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"v\n" +
	"\x16ListConnectionsRequest\x12!\n" +
	"\frequester_id\x18\x01 \x01(\tR\vrequesterId\x12\x1b\n" +
	"\tsystem_id\x18\x02 \x01(\tR\bsystemId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"\xae\x02\n" +
	"\x0eConnectionInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12(\n" +
	"\x10client_config_id\x18\x02 \x01(\x03R\x0eclientConfigId\x12\x1b\n" +
	"\tsource_ip\x18\x03 \x01(\tR\bsourceIp\x12+\n" +
	"\tbind_type\x18\x04 \x01(\x0e2\x0e.auth.BindTypeR\bbindType\x12!\n" +
	"\fconnected_at\x18\x05 \x01(\x03R\vconnectedAt\x12'\n" +
	"\x0fdisconnected_at\x18\x06 \x01(\x03R\x0edisconnectedAt\x12)\n" +
	"\x10authenticator_id\x18\a \x01(\tR\x0fauthenticatorId\x12!\n" +
	"\frequester_id\x18\b \x01(\tR\vrequesterId\"\xd1\x01\n" +
	"\x17ListConnectionsResponse\x12)\n" +
	"\x10authenticator_id\x18\x01 \x01(\tR\x0fauthenticatorId\x12.\n" +
	"\n" +
	"error_code\x18\x02 \x01(\x0e2\x0f.auth.ErrorCodeR\terrorCode\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x126\n" +
	"\vconnections\x18\x04 \x03(\v2\x14.auth.ConnectionInfoR\vconnections2\x86\x03\n" +
	"\x11ConnectionService\x12W\n" +
	"\x12RegisterConnection\x12\x1f.auth.RegisterConnectionRequest\x1a .auth.RegisterConnectionResponse\x12]\n" +
	"\x14UnregisterConnection\x12!.auth.UnregisterConnectionRequest\x1a\".auth.UnregisterConnectionResponse\x12i\n" +
	"\x18UnregisterAllConnections\x12%.auth.UnregisterAllConnectionsRequest\x1a&.auth.UnregisterAllConnectionsResponse\x12N\n" +
	"\x0fListConnections\x12\x1c.auth.ListConnectionsRequest\x1a\x1d.auth.ListConnectionsResponseB#Z!authenticator/api/proto/auth;authb\x06proto3"

var (
	file_api_proto_auth_connection_proto_rawDescOnce sync.Once
	file_api_proto_auth_connection_proto_rawDescData []byte
)

func file_api_proto_auth_connection_proto_rawDescGZIP() []byte {
	file_api_proto_auth_connection_proto_rawDescOnce.Do(func() {
		file_api_proto_auth_connection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_auth_connection_proto_rawDesc), len(file_api_proto_auth_connection_proto_rawDesc)))
	})
	return file_api_proto_auth_connection_proto_rawDescData
}

var file_api_proto_auth_connection_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_proto_auth_connection_proto_goTypes = []any{
	(*RegisterConnectionRequest)(nil),        // 0: auth.RegisterConnectionRequest
	(*RegisterConnectionResponse)(nil),       // 1: auth.RegisterConnectionResponse
	(*UnregisterConnectionRequest)(nil),      // 2: auth.UnregisterConnectionRequest
	(*UnregisterConnectionResponse)(nil),     // 3: auth.UnregisterConnectionResponse
	(*UnregisterAllConnectionsRequest)(nil),  // 4: auth.UnregisterAllConnectionsRequest
	(*UnregisterAllConnectionsResponse)(nil), // 5: auth.UnregisterAllConnectionsResponse
	(*ListConnectionsRequest)(nil),           // 6: auth.ListConnectionsRequest
	(*ConnectionInfo)(nil),                   // 7: auth.ConnectionInfo
	(*ListConnectionsResponse)(nil),          // 8: auth.ListConnectionsResponse
	(BindType)(0),                            // 9: auth.BindType
	(ErrorCode)(0),                           // 10: auth.ErrorCode
}
var file_api_proto_auth_connection_proto_depIdxs = []int32{
	9,  // 0: auth.RegisterConnectionRequest.bind_type:type_name -> auth.BindType
	10, // 1: auth.RegisterConnectionResponse.error_code:type_name -> auth.ErrorCode
	10, // 2: auth.UnregisterConnectionResponse.error_code:type_name -> auth.ErrorCode
	10, // 3: auth.UnregisterAllConnectionsResponse.error_code:type_name -> auth.ErrorCode
	9,  // 4: auth.ConnectionInfo.bind_type:type_name -> auth.BindType
	10, // 5: auth.ListConnectionsResponse.error_code:type_name -> auth.ErrorCode
	7,  // 6: auth.ListConnectionsResponse.connections:type_name -> auth.ConnectionInfo
	0,  // 7: auth.ConnectionService.RegisterConnection:input_type -> auth.RegisterConnectionRequest
	2,  // 8: auth.ConnectionService.UnregisterConnection:input_type -> auth.UnregisterConnectionRequest
	4,  // 9: auth.ConnectionService.UnregisterAllConnections:input_type -> auth.UnregisterAllConnectionsRequest
	6,  // 10: auth.ConnectionService.ListConnections:input_type -> auth.ListConnectionsRequest
	1,  // 11: auth.ConnectionService.RegisterConnection:output_type -> auth.RegisterConnectionResponse
	3,  // 12: auth.ConnectionService.UnregisterConnection:output_type -> auth.UnregisterConnectionResponse
	5,  // 13: auth.ConnectionService.UnregisterAllConnections:output_type -> auth.UnregisterAllConnectionsResponse
	8,  // 14: auth.ConnectionService.ListConnections:output_type -> auth.ListConnectionsResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_proto_auth_connection_proto_init() }
func file_api_proto_auth_connection_proto_init() {
	if File_api_proto_auth_connection_proto != nil {
		return
	}
	file_api_proto_auth_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_auth_connection_proto_rawDesc), len(file_api_proto_auth_connection_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_auth_connection_proto_goTypes,
		DependencyIndexes: file_api_proto_auth_connection_proto_depIdxs,
		MessageInfos:      file_api_proto_auth_connection_proto_msgTypes,
	}.Build()
	File_api_proto_auth_connection_proto = out.File
	file_api_proto_auth_connection_proto_goTypes = nil
	file_api_proto_auth_connection_proto_depIdxs = nil
}
