// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: api/proto/auth/stream.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerCommandType int32

const (
	ServerCommandType_SERVER_COMMAND_UNKNOWN       ServerCommandType = 0
	ServerCommandType_SERVER_COMMAND_PING          ServerCommandType = 1
	ServerCommandType_SERVER_COMMAND_DISCONNECT    ServerCommandType = 2
	ServerCommandType_SERVER_COMMAND_THROTTLE      ServerCommandType = 3
	ServerCommandType_SERVER_COMMAND_RELOAD_CONFIG ServerCommandType = 4
	ServerCommandType_SERVER_COMMAND_CUSTOM        ServerCommandType = 99
)

// Enum value maps for ServerCommandType.
var (
	ServerCommandType_name = map[int32]string{
		0:  "SERVER_COMMAND_UNKNOWN",
		1:  "SERVER_COMMAND_PING",
		2:  "SERVER_COMMAND_DISCONNECT",
		3:  "SERVER_COMMAND_THROTTLE",
		4:  "SERVER_COMMAND_RELOAD_CONFIG",
		99: "SERVER_COMMAND_CUSTOM",
	}
	ServerCommandType_value = map[string]int32{
		"SERVER_COMMAND_UNKNOWN":       0,
		"SERVER_COMMAND_PING":          1,
		"SERVER_COMMAND_DISCONNECT":    2,
		"SERVER_COMMAND_THROTTLE":      3,
		"SERVER_COMMAND_RELOAD_CONFIG": 4,
		"SERVER_COMMAND_CUSTOM":        99,
	}
)

func (x ServerCommandType) Enum() *ServerCommandType {
	p := new(ServerCommandType)
	*p = x
	return p
}

func (x ServerCommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerCommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_auth_stream_proto_enumTypes[0].Descriptor()
}

func (ServerCommandType) Type() protoreflect.EnumType {
	return &file_api_proto_auth_stream_proto_enumTypes[0]
}

func (x ServerCommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerCommandType.Descriptor instead.
func (ServerCommandType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_auth_stream_proto_rawDescGZIP(), []int{0}
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequesterId   string                 `protobuf:"bytes,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	SystemId      string                 `protobuf:"bytes,2,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_api_proto_auth_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_stream_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

func (x *SubscribeRequest) GetSystemId() string {
	if x != nil {
		return x.SystemId
	}
	return ""
}

type ServerCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Type          ServerCommandType      `protobuf:"varint,2,opt,name=type,proto3,enum=auth.ServerCommandType" json:"type,omitempty"`
	Payload       string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerCommand) Reset() {
	*x = ServerCommand{}
	mi := &file_api_proto_auth_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerCommand) ProtoMessage() {}

func (x *ServerCommand) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerCommand.ProtoReflect.Descriptor instead.
func (*ServerCommand) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_stream_proto_rawDescGZIP(), []int{1}
}

func (x *ServerCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *ServerCommand) GetType() ServerCommandType {
	if x != nil {
		return x.Type
	}
	return ServerCommandType_SERVER_COMMAND_UNKNOWN
}

func (x *ServerCommand) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *ServerCommand) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type BroadcastRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ServerCommandType      `protobuf:"varint,1,opt,name=type,proto3,enum=auth.ServerCommandType" json:"type,omitempty"`
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	TargetId      string                 `protobuf:"bytes,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"` // خالی = به همه کلاینت‌های subscribed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastRequest) Reset() {
	*x = BroadcastRequest{}
	mi := &file_api_proto_auth_stream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastRequest) ProtoMessage() {}

func (x *BroadcastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_stream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastRequest.ProtoReflect.Descriptor instead.
func (*BroadcastRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_stream_proto_rawDescGZIP(), []int{2}
}

func (x *BroadcastRequest) GetType() ServerCommandType {
	if x != nil {
		return x.Type
	}
	return ServerCommandType_SERVER_COMMAND_UNKNOWN
}

func (x *BroadcastRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *BroadcastRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

type BroadcastResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     ErrorCode              `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=auth.ErrorCode" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	SentCount     int32                  `protobuf:"varint,3,opt,name=sent_count,json=sentCount,proto3" json:"sent_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastResponse) Reset() {
	*x = BroadcastResponse{}
	mi := &file_api_proto_auth_stream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastResponse) ProtoMessage() {}

func (x *BroadcastResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_stream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastResponse.ProtoReflect.Descriptor instead.
func (*BroadcastResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_stream_proto_rawDescGZIP(), []int{3}
}

func (x *BroadcastResponse) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_ERROR_CODE_NONE
}

func (x *BroadcastResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *BroadcastResponse) GetSentCount() int32 {
	if x != nil {
		return x.SentCount
	}
	return 0
}

var File_api_proto_auth_stream_proto protoreflect.FileDescriptor

const file_api_proto_auth_stream_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/proto/auth/stream.proto\x12\x04auth\x1a\x1bapi/proto/auth/common.proto\"R\n" +
	"\x10SubscribeRequest\x12!\n" +
	"\frequester_id\x18\x01 \x01(\tR\vrequesterId\x12\x1b\n" +
	"\tsystem_id\x18\x02 \x01(\tR\bsystemId\"\x93\x01\n" +
	"\rServerCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12+\n" +
	"\x04type\x18\x02 \x01(\x0e2\x17.auth.ServerCommandTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"v\n" +
	"\x10BroadcastRequest\x12+\n" +
	"\x04type\x18\x01 \x01(\x0e2\x17.auth.ServerCommandTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\tR\btargetId\"\x87\x01\n" +
	"\x11BroadcastResponse\x12.\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x0e2\x0f.auth.ErrorCodeR\terrorCode\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"sent_count\x18\x03 \x01(\x05R\tsentCount*\xc1\x01\n" +
	"\x11ServerCommandType\x12\x1a\n" +
	"\x16SERVER_COMMAND_UNKNOWN\x10\x00\x12\x17\n" +
	"\x13SERVER_COMMAND_PING\x10\x01\x12\x1d\n" +
	"\x19SERVER_COMMAND_DISCONNECT\x10\x02\x12\x1b\n" +
	"\x17SERVER_COMMAND_THROTTLE\x10\x03\x12 \n" +
	"\x1cSERVER_COMMAND_RELOAD_CONFIG\x10\x04\x12\x19\n" +
	"\x15SERVER_COMMAND_CUSTOM\x10c2\x90\x01\n" +
	"\x14CommandStreamService\x12:\n" +
	"\tSubscribe\x12\x16.auth.SubscribeRequest\x1a\x13.auth.ServerCommand0\x01\x12<\n" +
	"\tBroadcast\x12\x16.auth.BroadcastRequest\x1a\x17.auth.BroadcastResponseB#Z!authenticator/api/proto/auth;authb\x06proto3"

var (
	file_api_proto_auth_stream_proto_rawDescOnce sync.Once
	file_api_proto_auth_stream_proto_rawDescData []byte
)

func file_api_proto_auth_stream_proto_rawDescGZIP() []byte {
	file_api_proto_auth_stream_proto_rawDescOnce.Do(func() {
		file_api_proto_auth_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_auth_stream_proto_rawDesc), len(file_api_proto_auth_stream_proto_rawDesc)))
	})
	return file_api_proto_auth_stream_proto_rawDescData
}

var file_api_proto_auth_stream_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_auth_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_auth_stream_proto_goTypes = []any{
	(ServerCommandType)(0),    // 0: auth.ServerCommandType
	(*SubscribeRequest)(nil),  // 1: auth.SubscribeRequest
	(*ServerCommand)(nil),     // 2: auth.ServerCommand
	(*BroadcastRequest)(nil),  // 3: auth.BroadcastRequest
	(*BroadcastResponse)(nil), // 4: auth.BroadcastResponse
	(ErrorCode)(0),            // 5: auth.ErrorCode
}
var file_api_proto_auth_stream_proto_depIdxs = []int32{
	0, // 0: auth.ServerCommand.type:type_name -> auth.ServerCommandType
	0, // 1: auth.BroadcastRequest.type:type_name -> auth.ServerCommandType
	5, // 2: auth.BroadcastResponse.error_code:type_name -> auth.ErrorCode
	1, // 3: auth.CommandStreamService.Subscribe:input_type -> auth.SubscribeRequest
	3, // 4: auth.CommandStreamService.Broadcast:input_type -> auth.BroadcastRequest
	2, // 5: auth.CommandStreamService.Subscribe:output_type -> auth.ServerCommand
	4, // 6: auth.CommandStreamService.Broadcast:output_type -> auth.BroadcastResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_auth_stream_proto_init() }
func file_api_proto_auth_stream_proto_init() {
	if File_api_proto_auth_stream_proto != nil {
		return
	}
	file_api_proto_auth_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_auth_stream_proto_rawDesc), len(file_api_proto_auth_stream_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_auth_stream_proto_goTypes,
		DependencyIndexes: file_api_proto_auth_stream_proto_depIdxs,
		EnumInfos:         file_api_proto_auth_stream_proto_enumTypes,
		MessageInfos:      file_api_proto_auth_stream_proto_msgTypes,
	}.Build()
	File_api_proto_auth_stream_proto = out.File
	file_api_proto_auth_stream_proto_goTypes = nil
	file_api_proto_auth_stream_proto_depIdxs = nil
}
