// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.1
// source: api/proto/auth/stream.proto

package auth

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CommandStreamService_Subscribe_FullMethodName = "/auth.CommandStreamService/Subscribe"
	CommandStreamService_Broadcast_FullMethodName = "/auth.CommandStreamService/Broadcast"
)

// CommandStreamServiceClient is the client API for CommandStreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ── ارتباط سرور → کلاینت ────────────────────────────────────────────────────
type CommandStreamServiceClient interface {
	// کلاینت subscribe می‌کند — سرور می‌تواند هر لحظه دستور push کند
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServerCommand], error)
	// admin/سرور دستور به یک یا همه کلاینت‌ها ارسال می‌کند
	Broadcast(ctx context.Context, in *BroadcastRequest, opts ...grpc.CallOption) (*BroadcastResponse, error)
}

type commandStreamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCommandStreamServiceClient(cc grpc.ClientConnInterface) CommandStreamServiceClient {
	return &commandStreamServiceClient{cc}
}

func (c *commandStreamServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServerCommand], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CommandStreamService_ServiceDesc.Streams[0], CommandStreamService_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, ServerCommand]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CommandStreamService_SubscribeClient = grpc.ServerStreamingClient[ServerCommand]

func (c *commandStreamServiceClient) Broadcast(ctx context.Context, in *BroadcastRequest, opts ...grpc.CallOption) (*BroadcastResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BroadcastResponse)
	err := c.cc.Invoke(ctx, CommandStreamService_Broadcast_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommandStreamServiceServer is the server API for CommandStreamService service.
// All implementations must embed UnimplementedCommandStreamServiceServer
// for forward compatibility.
//
// ── ارتباط سرور → کلاینت ────────────────────────────────────────────────────
type CommandStreamServiceServer interface {
	// کلاینت subscribe می‌کند — سرور می‌تواند هر لحظه دستور push کند
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[ServerCommand]) error
	// admin/سرور دستور به یک یا همه کلاینت‌ها ارسال می‌کند
	Broadcast(context.Context, *BroadcastRequest) (*BroadcastResponse, error)
	mustEmbedUnimplementedCommandStreamServiceServer()
}

// UnimplementedCommandStreamServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommandStreamServiceServer struct{}

func (UnimplementedCommandStreamServiceServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[ServerCommand]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedCommandStreamServiceServer) Broadcast(context.Context, *BroadcastRequest) (*BroadcastResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Broadcast not implemented")
}
func (UnimplementedCommandStreamServiceServer) mustEmbedUnimplementedCommandStreamServiceServer() {}
func (UnimplementedCommandStreamServiceServer) testEmbeddedByValue()                              {}

// UnsafeCommandStreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommandStreamServiceServer will
// result in compilation errors.
type UnsafeCommandStreamServiceServer interface {
	mustEmbedUnimplementedCommandStreamServiceServer()
}

func RegisterCommandStreamServiceServer(s grpc.ServiceRegistrar, srv CommandStreamServiceServer) {
	// If the following call panics, it indicates UnimplementedCommandStreamServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CommandStreamService_ServiceDesc, srv)
}

func _CommandStreamService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CommandStreamServiceServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, ServerCommand]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CommandStreamService_SubscribeServer = grpc.ServerStreamingServer[ServerCommand]

func _CommandStreamService_Broadcast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandStreamServiceServer).Broadcast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommandStreamService_Broadcast_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandStreamServiceServer).Broadcast(ctx, req.(*BroadcastRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CommandStreamService_ServiceDesc is the grpc.ServiceDesc for CommandStreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommandStreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.CommandStreamService",
	HandlerType: (*CommandStreamServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Broadcast",
			Handler:    _CommandStreamService_Broadcast_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _CommandStreamService_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/auth/stream.proto",
}
